[package]
name = "autoagents-work-verify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
autoagents = {version = "0.3.0", features = ["openai"]}
autoagents-derive = "0.3.0"
dotenv = "0.15.0"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
meval = "0.2.0"
